export const EN = {
    subTitle: 'WELCOME',
    pauseBtn: 'Pause/Start',
    settingsBtn: 'Settings',
    fireBtn: 'FIRE!',
    mode: 'GAME MODE:',
    playersNum: 'PvP PLAYERS:',
    sound: 'SOUNDS:',
    soundON: 'ON',
    soundOFF: 'OFF',
    lang: 'LANGUAGE:',
    auth: 'LOGIN/SIGNUP',
    authOut: 'LOGOUT',
    titlePopup: {
        login: 'Login',
        registration: 'Registration',
    },
    titleError: `You've entered an incorrect email address or password.`,
    inputName: 'Username',
    inputEmail: 'E-mail',
    inputPassword: 'Password',
    loginBtn: 'LOGIN',
    signupBtn: 'SIGN UP',
    changeBtn: {
        signup: 'Sign UP',
        login: 'Login',
    },
    inst: 'HOW TO PLAY',
    start: 'START GAME',
    back: 'BACK TO GAME',
    menu: 'BACK TO MAIN MENU',
    winnerText: 'wins the game! Congratulations!',
    restart: 'RESTART GAME',
    gamePaused: 'PAUSE',
    screen: {
        angle: 'Angle: ',
        power: 'Power: ',
        time: 'TIME:',
        wind: 'Wind: ',
        windSpeed: 'm/s',
        player: 'Player: ',
    },
    instructions: {
        header: 'HOW TO PLAY',
        info: 'You can use your keyboard or game console buttons to control the tank and menu',
        up: '↑ | UP - increase shot power or select previous menu item',
        down: '↓ | DOWN - reduce shot power or select next menu item',
        left: '← | LEFT - increase tank canon angle or switch to prevoius menu option',
        right: '→ | RIGHT - reduce tank canon angle or switch to next menu option',
        space: 'SPACE | FIRE - fire the projectile of press menu button',
        pause: 'PAUSE(kbrd) | Pause/Start - pause/resume game, start game with current settings or close ingame menu',
        esc: 'ESCAPE | Settings - open/close settings menu',
        back: 'BACK TO MENU',
    },
};

export const RU = {
    subTitle: 'ПРИВЕТ',
    pauseBtn: 'Пауза/Старт',
    settingsBtn: 'Настройки',
    fireBtn: 'ОГОНЬ!',
    mode: 'ТИП ИГРЫ:',
    playersNum: 'PvP ИГРОКИ:',
    sound: 'ЗВУКИ:',
    soundON: 'ВКЛ',
    soundOFF: 'ВЫКЛ',
    lang: 'ЯЗЫК:',
    auth: 'ВХОД/РЕГИСТР.',
    authOut: 'ВЫЙТИ',
    titlePopup: {
        login: 'Войти',
        registration: 'Регистрация',
    },
    titleError: 'Вы ввели неверный адрес эл.почты или пароль.',
    inputName: 'Никнейм',
    inputEmail: 'Эл. почта',
    inputPassword: 'Пароль',
    loginBtn: 'ВОЙТИ',
    signupBtn: 'РЕГИСТРАЦИЯ',
    changeBtn: {
        signup: 'Регистрация',
        login: 'Войти',
    },
    inst: 'КАК ИГРАТЬ',
    start: 'НАЧАТЬ ИГРУ',
    back: 'ВЕРНУТЬСЯ В ИГРУ',
    menu: 'ВЕРНУТЬСЯ В ГЛАВНОЕ МЕНЮ',
    winnerText: 'побеждает в игре! Поздравляем!',
    restart: 'ПЕРЕЗАПУСТИТЬ ИГРУ',
    gamePaused: 'ПАУЗА',
    screen: {
        angle: 'Угол: ',
        power: 'Сила: ',
        time: 'ВРЕМЯ:',
        wind: 'Ветер: ',
        windSpeed: 'м/с',
        player: 'Игрок: ',
    },
    instructions: {
        header: 'КАК ИГРАТЬ',
        info:
            'Вы можете использовать клавиши клавиатуры или кнопки виртуальной консоли, чтобы контролировать танк или меню',
        up: '↑ | Вверх - увеличить силу выстрела или выбрать предыдущий пункт меню',
        down: '↓ | Вних - уменьшить силу выстрела или выбрать следующий пункт меню',
        left: '← | Влево - увеличить угол пушки танка или переключиться на предыдущую опцию пункта меню',
        right: '→ | Вправо - уменьшить угол пушки танка или переключиться на следующую опцию пункта меню',
        space: 'ПРОБЕЛ | ОГОНЬ - запустить снаряд или нажать на кнопку меню',
        pause:
            'PAUSE(клав) | Пауза/Старт - приостановить/возобновить игру, начать игру с текущими настройками или закрыть меню',
        esc: 'ESCAPE | Настройки - открыть/закрыть меню настроек',
        back: 'НАЗАД В МЕНЮ',
    },
};
